### ISSUE TITLE
Can not set SELENIUM_PORT env variable to 4444

### ISSUE THREAD

**Issue by aleksz** [infradna/selenium-client-factory#2]
Hi,

  There seems to be an integer formatting issue:

java.lang.IllegalArgumentException: Invalid URL: sauce-ondemand:?os=Linux&browser=firefox&browser-version=11&job-name=com.gmail.at.zhuikov.aleksandr.it.WebDriverIT.userCreatesOrder
    at com.saucelabs.sauce_ondemand.driver.SauceOnDemandSPIImpl.createWebDriver(SauceOnDemandSPIImpl.java:169)
    at com.saucelabs.selenium.client.factory.SeleniumFactory.createWebDriver(SeleniumFactory.java:291)
    at com.saucelabs.selenium.client.factory.SeleniumFactory.createWebDriverInstance(SeleniumFactory.java:275)
    at com.saucelabs.selenium.client.factory.SeleniumFactory.createWebDriver(SeleniumFactory.java:84)
    at com.gmail.at.zhuikov.aleksandr.it.AbstractWebDriverTest.createDriver(AbstractWebDriverTest.java:38)
    at com.gmail.at.zhuikov.aleksandr.it.AbstractWebDriverTest.openPage(AbstractWebDriverTest.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
    at org.junit.rules.RunRules.evaluate(RunRules.java:18)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.net.MalformedURLException: For input string: "4,444"
    at java.net.URL.<init>(URL.java:601)
    at java.net.URL.<init>(URL.java:464)
    at java.net.URL.<init>(URL.java:413)
    at com.saucelabs.sauce_ondemand.driver.SauceOnDemandSPIImpl.createWebDriver(SauceOnDemandSPIImpl.java:155)
    ... 31 more

See http://stackoverflow.com/questions/1942118/how-do-i-format-a-long-integer-as-a-string-without-separator-in-java

**Comment by rossrowe** [comment]
Hi Aleksandr, are you using the Jenkins Sauce OnDemand plugin to invoke the selenium-client-factory?  I just committed and deployed a fix for the Jenkins plugin to ensure that the SELENIUM_PORT environment variable does not include a comma, which I think is the underlying issue.

Regardless, I'll update the selenium-client-factory code to convert the value of the SELENIUM_PORT environment variable into a Integer.

Cheers,

Ross

**Comment by aleksz** [comment]
It's already integer:

``` java
        String portAsString = readPropertyOrEnv(SELENIUM_PORT, null);
        int port;
        if (portAsString == null || portAsString.equals("")) {
            port = DEFAULT_WEBDRIVER_PORT;
        } else {
            port = Integer.parseInt(portAsString);
        }
```

but then comes this:

``` java
                            MessageFormat.format(
                                    "http://{2}:{3}@{0}:{1}/wd/hub",
                                    host, port,
                                    getFirstParameter(paramMap,"username"),
                                    getFirstParameter(paramMap,"access-key")
```

I was able to reproduce it on my machine and I'm sure that SELENIUM_PORT value is 4444, without coma. This seems to be a normal behavior of MessageFormat, check this link http://stackoverflow.com/questions/1942118/how-do-i-format-a-long-integer-as-a-string-without-separator-in-java

**Comment by rossrowe** [comment]
Ah sorry, my bad...I was looking at the WebDriver code (which isn't parsing the Integer) and forgot about the Selenium code.  I'll commit a fix for this asap.

Cheers,

Ross

**Comment by rossrowe** [comment]
Hi again, can I check with you to see what version of the code you're using?  The code was changed to pass the port as a String (without converting it to an Integer) back in April.  I've now deployed the latest version of the code as version 2.5 to the Sauce Labs Maven repository (https://repository-saucelabs.forge.cloudbees.com/release)

Cheers,

Ross

**Comment by aleksz** [comment]
Hi, sorry for late answer. I've got sauce-ondemand-driver-2.2

**Comment by aleksz** [comment]
Ok, I think I'm using wrong repo, http://maven.jenkins-ci.org:8081/content/repositories/releases. It says 2.2 is the latest. I will switch to 2.5 from Sauce Labs repo

**Comment by Khalith-Basha** [comment]
Thanks :) @aleksz
